name: Release
on:
  push:
    branches:
      - main

permissions:
  contents: read # for checkout

jobs:
  release:
    name: Release
    environment: release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to publish a GitHub release
      issues: write # to comment on released issues
      pull-requests: write # to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js and pnpm
        uses: pnpm/action-setup@v4
        with:
          node-version: "20" # unified Node.js version
          pnpm-version: "9"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Verify integrity of dependencies
        run: pnpm audit

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm release

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: . # Adjust path to include only the files necessary for deployment

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: release # Ensures this job runs only after 'release' completes
    environment: production
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: artifact

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Deploy to Production
        run: |
          # Add commands to deploy to production, e.g., triggering a server update or syncing files
          echo "Deploying to production..."
