name: CI/CD
on:
  push:
    branches:
      - main

permissions:
  contents: read # for checkout

jobs:
  build:
    name: Audit and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Audit dependencies
        run: pnpm audit

      - name: Build
        run: pnpm build # Add the correct build command for your project

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: . # Adjust path to include only built files needed for release and deployment

  release:
    name: Release
    needs: build # Ensures this job runs only after 'build' completes
    environment: release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to publish a GitHub release
      issues: write # to comment on released issues
      pull-requests: write # to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm release

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: release # Ensures this job runs only after 'release' completes
    environment: production
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Deploy to Production
        run: |
          # Add commands to deploy to production, e.g., triggering a server update or syncing files
          echo "Deploying to production..."
